name: 'init-commands'

on:
  workflow_dispatch:

env:
  tf_version: '1.4.6'
  tg_version: '0.46.3'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@bug/permissions-fix-34
        env:
          INPUT_PRE_EXEC_0: ""
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'simple-project'
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

  plan:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v1
        env:
          INPUT_PRE_EXEC_0: 'curl -sLO https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip && unzip -q awscli-exe-linux-x86_64.zip && ./aws/install'
          INPUT_PRE_EXEC_1: |
            git config --global --list
          INPUT_POST_EXEC_1: |
            ls -lahrt
          INPUT_POST_EXEC_2: |
            pwd
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'simple-project'
          tg_command: 'plan'
          tg_comment: 1
