name: 'pass-output'

on:
  workflow_dispatch:

env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'
  working_dir: 'dependencies-project'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2

        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

  apply:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run-all plan -out tfplan --terragrunt-log-level debug'

      - name: Apply
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run-all apply tfplan --terragrunt-log-level debug'