name: 'pass-output'

on:
  workflow_dispatch:

env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'
  working_dir: 'dependencies-project'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2

        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

  apply:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run-all plan -out tfplan --terragrunt-log-level debug'

      - name: Tree
        shell: bash
        run: "tree"

      - name: Plan output app1
        shell: bash
        run: "ls -lahrt dependencies-project/app"

      - name: Plan output module1
        shell: bash
        run: "ls -lahrt dependencies-project/module1"

      - name: Plan output module2
        shell: bash
        run: "ls -lahrt dependencies-project/module2"

      - name: Apply
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run-all --terragrunt-log-level debug apply tfplan'