name: 'permissions-check'

on:
  workflow_dispatch:

env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'

jobs:

  plan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: debug 1
        shell:  bash
        run: |
          ls -lahrt -n simple-project
          whoami


      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        env:
          INPUT_PRE_EXEC_0: "ls -lahrt -n simple-project"
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'simple-project'
          tg_command: 'plan'
          tg_comment: 1

      - name: debug 2
        shell:  bash
        run: |
          ls -lahrt -n simple-project
          whoami
      - name: debug 3
        shell:  bash
        run: |
          ls -lahrt  simple-project
          whoami

