name: 'private-repo'

on:
  workflow_dispatch:

env:
  tf_version: '1.4.6'
  tg_version: '0.46.3'
  working_dir: 'private-repo'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create directory to pass ssh-agent socket
        run: "mkdir -p /home/runner/work/_temp/_github_workflow"
        shell: bash

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-auth-sock: "/home/runner/work/_temp/_github_workflow/ssh-agent.sock"

      - name: Plan
        uses: gruntwork-io/terragrunt-action@bug/vars-checking
        env:
            SSH_AUTH_SOCK: "/github/workflow/ssh-agent.sock"
            INPUT_PRE_EXEC_0: |
              git config --global url."https://denis256:${{secrets.PAT_TOKEN}}@github.com".insteadOf "https://github.com"
            INPUT_PRE_EXEC_1: |
              git config --global --list
            INPUT_PRE_EXEC_2: |
              cat ~/.gitconfig
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run-all plan --terragrunt-log-level debug'
