name: 'remote-repo'

on:
  workflow_dispatch:

env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'

jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'remote-repo'
          tg_command: 'init'

  plan:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'remote-repo'
          tg_command: 'plan'

  deploy:
    runs-on: ubuntu-latest
    needs: [plan]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'remote-repo'
          tg_command: 'apply'


