name: 'simple-project'

on:
  workflow_dispatch:

env:
  tf_version: '1.4.6'
  tg_version: 'latest'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Check terragrunt HCL
        uses: denis256/tg-gh-action@master
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'simple-project'
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

  plan:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Plan
        uses: denis256/tg-gh-action@master
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'simple-project'
          tg_command: 'plan'

  deploy:
    runs-on: ubuntu-latest
    needs: [plan]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Deploy
        uses: denis256/tg-gh-action@master
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'simple-project'
          tg_command: 'apply'

  destroy:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Deploy
        uses: denis256/tg-gh-action@master
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'simple-project'
          tg_command: 'destroy'

